# This is a basic workflow to help you get started with Actions

name: Talaria-GUI-Packaging-pipeline

# Controls when the action will run. 
on:
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Preparing Environment
        run: |
          mkdir Talaria.AppDir

          cp * Talaria.AppDir

          cd Talaria.AppDir

          echo "[Desktop Entry]
          Name=Talaria
          Icon=icon
          Type=Application
          Categories=Utility" > Talaria.desktop

          echo "#!/bin/sh
          cd "$(dirname "$0")"
          exec ./base-gui.sh" > AppRun

          #icon
          #wget raw.github #####################

          chmod +x AppRun Talaria base-gui.sh 
